// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3756ea64fda35e31, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type AuthTokenResponse struct {
	AccessToken          string   `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthTokenResponse) Reset()         { *m = AuthTokenResponse{} }
func (m *AuthTokenResponse) String() string { return proto.CompactTextString(m) }
func (*AuthTokenResponse) ProtoMessage()    {}
func (*AuthTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_3756ea64fda35e31, []int{1}
}
func (m *AuthTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthTokenResponse.Unmarshal(m, b)
}
func (m *AuthTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthTokenResponse.Marshal(b, m, deterministic)
}
func (dst *AuthTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthTokenResponse.Merge(dst, src)
}
func (m *AuthTokenResponse) XXX_Size() int {
	return xxx_messageInfo_AuthTokenResponse.Size(m)
}
func (m *AuthTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthTokenResponse proto.InternalMessageInfo

func (m *AuthTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*AuthTokenResponse)(nil), "AuthTokenResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_auth_3756ea64fda35e31) }

var fileDescriptor_auth_3756ea64fda35e31 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x62, 0xe7, 0x62, 0x75, 0xcd, 0x2d, 0x28, 0xa9, 0x54,
	0x32, 0xe3, 0x12, 0x74, 0x2c, 0x2d, 0xc9, 0x08, 0xc9, 0xcf, 0x4e, 0xcd, 0x0b, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x52, 0xe4, 0xe2, 0x49, 0x4c, 0x4e, 0x4e, 0x2d, 0x2e, 0x8e, 0x2f,
	0x01, 0x89, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x71, 0x43, 0xc4, 0xc0, 0x4a, 0x8d, 0x8c,
	0xb8, 0xb8, 0x41, 0xfa, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x94, 0xb9, 0x58, 0xc1,
	0xe2, 0x42, 0x6c, 0x7a, 0x60, 0x73, 0xa5, 0x84, 0xf4, 0x30, 0x8c, 0x4d, 0x62, 0x03, 0xdb, 0x6d,
	0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x90, 0xad, 0x49, 0xbe, 0x89, 0x00, 0x00, 0x00,
}
